name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 4

    - name: Check size
      run: |
        $HOME/.local/bin/lizard | bash .github/workflows/check_ccn.sh 100
        
    - name: compile the code 
      run: gcc -Wall -Wextra -o tdd_buckets -g *.c
      
    - name: run
      run: ./tdd_buckets
