name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: compile the code 
      run: g++ -Wall -Wextra -o tdd_buckets *.c*
    - name: run
      run: ./tdd_buckets
